
export const localNamesBy3 = {
  abk: 'Аҧсуа',
  aar: 'Afaraf',
  afr: 'Afrikaans',
  aka: 'Akan',
  sqi: 'Shqip',
  amh: 'አማርኛ',
  ara: 'العربية',
  arg: 'Aragonés',
  hye: 'Հայերեն',
  asm: 'অসমীয়া',
  ava: 'Авар',
  ave: 'avesta',
  aym: 'Aymar',
  aze: 'Azərbaycanca',
  bam: 'Bamanankan',
  bak: 'Башҡортса',
  eus: 'Euskara',
  bel: 'Беларуская',
  ben: 'বাংলা',
  bih: 'भोजपुरी',
  bis: 'Bislama',
  bos: 'Bosanski',
  bre: 'Brezhoneg',
  bul: 'Български',
  mya: 'မြန်မာဘာသာ',
  cat: 'Català',
  cha: 'Chamoru',
  che: 'Нохчийн',
  nya: 'Chichewa',
  zho: '中文',
  chv: 'Чӑвашла',
  cor: 'Kernewek',
  cos: 'Corsu',
  cre: 'ᓀᐦᐃᔭᐍᐏᐣ',
  hrv: 'Hrvatski',
  ces: 'Čeština',
  dan: 'Dansk',
  div: 'Divehi',
  nld: 'Nederlands',
  dzo: 'རྫོང་ཁ',
  eng: 'English',
  epo: 'Esperanto',
  est: 'Eesti',
  ewe: 'Eʋegbe',
  fao: 'Føroyskt',
  fij: 'Na Vosa Vaka-Viti',
  fin: 'Suomi',
  fra: 'Français',
  ful: 'Fulfulde',
  glg: 'Galego',
  kat: 'ქართული',
  deu: 'Deutsch',
  ell: 'Ελληνικά',
  grn: 'Avañe\'ẽ',
  guj: 'ગુજરાતી',
  hat: 'Kreyòl Ayisyen',
  hau: 'هَوُسَ',
  heb: 'עברית',
  her: 'Otjiherero',
  hin: 'हिन्दी',
  hmo: 'Hiri Motu',
  hun: 'Magyar',
  ina: 'Interlingua',
  ind: 'Bahasa Indonesia',
  ile: 'Interlingue',
  gle: 'Gaeilge',
  ibo: 'Igbo',
  ipk: 'Iñupiak',
  ido: 'Ido',
  isl: 'Íslenska',
  ita: 'Italiano',
  iku: 'ᐃᓄᒃᑎᑐᑦ',
  jpn: '日本語',
  jav: 'Basa Jawa',
  kal: 'Kalaallisut',
  kan: 'ಕನ್ನಡ',
  kau: 'Kanuri',
  kas: 'كشميري',
  kaz: 'Қазақша',
  khm: 'ភាសាខ្មែរ',
  kik: 'Gĩkũyũ',
  kin: 'Kinyarwanda',
  kir: 'Кыргызча',
  kom: 'Коми',
  kon: 'Kongo',
  kor: '한국어',
  kur: 'Kurdî',
  kua: 'Kuanyama',
  lat: 'Latina',
  ltz: 'Lëtzebuergesch',
  lug: 'Luganda',
  lim: 'Limburgs',
  lin: 'Lingála',
  lao: 'ພາສາລາວ',
  lit: 'Lietuvių',
  lub: 'Tshiluba',
  lav: 'Latviešu',
  glv: 'Gaelg',
  mkd: 'Македонски',
  mlg: 'Malagasy',
  msa: 'Bahasa Melayu',
  mal: 'മലയാളം',
  mlt: 'Malti',
  mri: 'Māori',
  mar: 'मराठी',
  mah: 'Kajin M̧ajeļ',
  mon: 'Монгол',
  nau: 'Dorerin Naoero',
  nav: 'Diné Bizaad',
  nde: 'isiNdebele',
  nep: 'नेपाली',
  ndo: 'Owambo',
  nob: 'Norsk (Bokmål)',
  nno: 'Norsk (Nynorsk)',
  nor: 'Norsk',
  iii: 'ꆈꌠ꒿ Nuosuhxop',
  nbl: 'isiNdebele',
  oci: 'Occitan',
  oji: 'ᐊᓂᔑᓈᐯᒧᐎᓐ',
  chu: 'Словѣ́ньскъ',
  orm: 'Afaan Oromoo',
  ori: 'ଓଡି଼ଆ',
  oss: 'Ирон æвзаг',
  pan: 'ਪੰਜਾਬੀ',
  pli: 'पाऴि',
  fas: 'فارسی',
  pol: 'Polski',
  pus: 'پښتو',
  por: 'Português',
  que: 'Runa Simi',
  roh: 'Rumantsch',
  run: 'Kirundi',
  ron: 'Română',
  rus: 'Русский',
  san: 'संस्कृतम्',
  srd: 'Sardu',
  snd: 'سنڌي‎',
  sme: 'Sámegiella',
  smo: 'Gagana Sāmoa',
  sag: 'Sängö',
  srp: 'Српски',
  gla: 'Gàidhlig',
  sna: 'ChiShona',
  sin: 'සිංහල',
  slk: 'Slovenčina',
  slv: 'Slovenščina',
  som: 'Soomaaliga',
  sot: 'Sesotho',
  spa: 'Español',
  sun: 'Basa Sunda',
  swa: 'Kiswahili',
  ssw: 'SiSwati',
  swe: 'Svenska',
  tam: 'தமிழ்',
  tel: 'తెలుగు',
  tgk: 'Тоҷикӣ',
  tha: 'ภาษาไทย',
  tir: 'ትግርኛ',
  bod: 'བོད་ཡིག',
  tuk: 'Türkmençe',
  tgl: 'Tagalog',
  tsn: 'Setswana',
  ton: 'faka Tonga',
  tur: 'Türkçe',
  tso: 'Xitsonga',
  tat: 'Татарча',
  twi: 'Twi',
  tah: 'Reo Mā’ohi',
  uig: 'ئۇيغۇرچه',
  ukr: 'Українська',
  urd: 'اردو',
  uzb: 'O‘zbek',
  ven: 'Tshivenḓa',
  vie: 'Tiếng Việt',
  vol: 'Volapük',
  wln: 'Walon',
  cym: 'Cymraeg',
  wol: 'Wolof',
  fry: 'Frysk',
  xho: 'isiXhosa',
  yid: 'ייִדיש',
  yor: 'Yorùbá',
  zha: 'Cuengh',
  zul: 'isiZulu',
};
