# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  NODE_ENV: development

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: npm ci
    - run: npm run lint

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16, 18, 20]

    steps:
    - uses: actions/checkout@v3
    - name: Build with Node 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: npm ci
    - run: npm run postinstall
    - run: npm run build
    - name: Test with Node 10
      uses: actions/setup-node@v3
      with:
        node-version: 10
        cache: 'npm'
    - run: npm run test-cjs
    - name: Test with Node ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm test
